// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCQ6716OAw-0jTKG2rA-ll3ZghAHMJ5PM',
    appId: '1:967327593812:web:3d7596fb92b68daffd44c1',
    messagingSenderId: '967327593812',
    projectId: 'hananori-pui',
    authDomain: 'hananori-pui.firebaseapp.com',
    databaseURL: 'https://hananori-pui-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hananori-pui.firebasestorage.app',
    measurementId: 'G-BE9XV17S7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMLTyfrFTJV36DjkM6DqmPtZ-vFg42ql0',
    appId: '1:967327593812:android:58ffa49338925ab6fd44c1',
    messagingSenderId: '967327593812',
    projectId: 'hananori-pui',
    databaseURL: 'https://hananori-pui-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hananori-pui.firebasestorage.app',
  );
}
